#pragma once

// SDK
#include "SDK/EARS_Common/SafePtr.h"
#include "SDK/EARS_Framework/Core/Camera/Camera.h"

namespace EARS::Modules
{
	struct MarketingCameraSettings
	{
		float m_MoveSpeed = 12.0f;			// world units/sec, full stick deflection
		float m_MoveSpeedModifier = 5.0f;	// multiplier while the speed-up button is held
		float m_RotateSpeed = 2.25f;		// radians/sec, full stick deflection

		// Gamepad rotation input smoothing time constants (seconds). Exponential, so it's frame-rate
		// independent. Fast attack when accelerating, slower release so the camera coasts to a stop.
		float m_RotationSmoothRampUp = 0.08f; // lower = snappier response
		float m_RotationSmoothDecay = 0.19f; // higher = longer coast-out

		// Whether stick rotation uses the ramp-up/coast-out smoothing above.
		// When off, the stick drives rotation speed directly.
		bool m_bGamepadRotationSmoothing = false;

		// Mouse look multiplier, applied on top of the game's own Mouse.Sensitivity option
		// (which is already baked into the deltas the camera receives).
		float m_MouseSensitivity = 1.0f;

		// Optional mouse look smoothing, for buttery cinematic pans. Off by default because
		// it trades away the 1:1 hand-to-camera feel: the camera lags the hand slightly and
		// coasts briefly after it stops.
		bool m_bMouseSmoothing = false;
		float m_MouseSmoothTime = 0.05f; // time constant (seconds); higher = smoother/laggier
	};

	class MarketingCamera : public EARS::Framework::Camera
	{
	public:

		MarketingCamera(const EARS::Framework::CameraInfo& InCameraInfo);

		//~ Begin EARS::Framework::CameraInfo Interface
		virtual void Init(uint32_t PlayerID, bool bResetCamera) override;
		virtual void Update(float DeltaTime) override;
		//~ End EARS::Framework::CameraInfo Interface

		// all of these are global values
		static MarketingCameraSettings& GetCameraSettings();

	private:

		// Smoothed gamepad rotation input, so the camera accelerates in and coasts out instead of
		// snapping to the raw stick value. Mouse look is applied directly and bypasses this.
		float m_SmoothedYawInput = 0.0f;
		float m_SmoothedPitchInput = 0.0f;

		// Smoothed mouse velocity (counts/sec), only used while the optional mouse smoothing
		// setting is enabled. Kept as a velocity so the smoothing is frame-rate independent.
		float m_SmoothedMouseVelocityX = 0.0f;
		float m_SmoothedMouseVelocityY = 0.0f;

		// When set, the next mouse delta is discarded instead of applied. Set on Init and while
		// the ImGui menu owns the cursor, where the game's mouse delta tracking is unreliable.
		bool m_bSwallowMouseDelta = true;
	};

	class MarketingCameraInfo : public EARS::Framework::CameraInfo
	{
	public:

		MarketingCameraInfo();

		//~ Begin EARS::Framework::CameraInfo Interface
		virtual EARS::Framework::Camera* Create() override;
		//~ End EARS::Framework::CameraInfo Interface

		MarketingCamera* GetActiveCamera() const { return m_ActiveCamera.GetPtr(); }

	private:

		// active camera generated by create.
		// Once the camera is destroyed, this is reset.
		SafePtr<MarketingCamera> m_ActiveCamera;

	};
}